name: Build
on:
  push:
    # paths:
    #   - '*.js'
    #   - '*.jsx'
    #   - '*.ts'
    #   - '*.tsx'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: npm install, build, and test
        run: |
          set -xe
          git config user.name github-actions
          git config user.email github-actions@github.com
          git_hash=$(git rev-parse --short "$GITHUB_SHA")
          git_branch=${GITHUB_REF##*/}
          yarn install
          yarn test
          yarn build
          yarn version --prerelease --preid "$git_branch-$git_hash"
          git push origin HEAD --tags
        env:
          CI: true
      - name: Publish
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
          registry-url: 'https://npm.pkg.github.com'
      - run: yarn publish --tag next
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
