name: Build - Release
on:
  release:
    types: [created]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: npm install, build, and test
        run: |
          set -xe
          git config user.name github-actions
          git config user.email github-actions@github.com
          git_version=${GITHUB_REF##*/}
          yarn install
          yarn test
          yarn build
          yarn version --new-version "$git_version"
          git push origin HEAD
        env:
          CI: true
      - name: Publish
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
          registry-url: "https://npm.pkg.github.com"
      - run: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
